Add skiperrors flag
Dynatrace/dynatrace-service-broker pull request #3
Opened 2019-03-22 08:32 UTC by DTMad

2019-03-22 08:53 UTC, arthfl requested changes

2019-03-22 08:53 UTC, arthfl commented on README.md
> +| `skiperrors` | (Optional) Configures the OneAgent error handling.
Please improve the description here.

2019-03-22 08:53 UTC, arthfl commented on manifest.yml
> +    DYNATRACE_SERVICE_PLANS: '{"A":{"name":"A","environmentid":"kwlxxxxx","apitoken":"xxxxxxxxxxx","apiurl":"https://yourmanagedcluster.com/api", "skiperrors":"false"},"B":{"name":"B","environmentid"
There's a leading whitespace before the first `skiperrors`

2019-03-25 08:03 UTC, arthfl approved these changes

2019-03-25 08:04 UTC, merged

2019-03-25 08:09 UTC, lrgar commented
Java has the "boolean" value type aside from the boxed Boolean class. But LGTM otherwise.